site_name: sudoblark.github-actions.library
repo_url: https://github.com/sudoblark/sudoblark.github-actions.library
repo_name: sudoblark/sudoblark.github-actions.library
site_url: https://sudoblark.github.io/sudoblark.github-actions.library/
site_author: Benjamin Clark
site_description: ->
  Library of semantically versioned](https://semver.org) actions, intended to be used as off-the-shelf, standardised,
  building blocks for CI/CD processes involving GitHub Actions.
copyright: BSD-3
site_dir: site
docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt

extra:
  version:
    provider: mike
nav:
  - "Home": 'index.md'
  - "Getting Started":
      - "What are composite actions": "getting-started/what-are-composite-actions.md"
      - "How to utilise": "getting-started/how-to-utilise.md"
  - "Release Notes":
      - "1.0.0": "release-notes/1.0.0.md"
  - "Composite Actions":
      - "Terraform":
          - "plan": "composite-actions/terraform/plan.md"
          - "apply": "composite-actions/terraform/apply.md"

plugins:
  - search